8000000 constant OSC_FREQ
5000 constant INTERRUPT_FREQ
1 constant PRESCALER
OSC_FREQ 4 / INTERRUPT_FREQ / PRESCALER / constant PERIOD
PERIOD 100 / 1 - constant PER_COUNTS
PERIOD PER_COUNTS 100 * - 3 - constant PER_REMAINDER

: main PER_REMAINDER ;
